[build]
rustflags = [
    "-Z", "threads=8",
    "-C", "link-arg=-Wl,-z,pack-relative-relocs",
    "-C", "symbol-mangling-version=v0",
    "-C", "link-args=-Wl,--icf=all"
]

[target.'cfg(target_os = "linux")']
rustflags = [
    "-Z", "threads=8",
    "-C", "link-arg=-fuse-ld=mold",
    "-C", "link-arg=-Wl,-z,pack-relative-relocs",
    "-C", "symbol-mangling-version=v0",
    "-C", "link-args=-Wl,--icf=all"
]